Add mime filter
ihadeed/cordova-filechooser pull request #3
Opened 2018-10-18 16:23 UTC by hibeekaey

2018-10-27 17:08 UTC, ihadeed requested changes

2018-10-27 17:08 UTC, ihadeed commented on www/fileChooser.js
> +    open: function (filter, success, failure) {
can we maintain backwards compatibility here? 

```
if (typeof filter === 'function') {
  failure = success;
  success = filter;
  filter= [];
}
```

2018-10-28 18:27 UTC, hibeekaey commented on www/fileChooser.js
> +    open: function (filter, success, failure) {
Yes, I've worked on it. I also cleaned up the README.

2018-11-26 08:55 UTC, ansarikhurshid786 commented
is filter working?

2018-11-26 13:54 UTC, hibeekaey commented
Yes, filter is working.

2018-11-27 06:16 UTC, ansarikhurshid786 commented
How to add mime type ? can you give me one please because I can't find it in documentation or anywhere else

2018-11-27 08:25 UTC, hibeekaey commented
You can find the updated repo and documentation here, https://github.com/hibeekaey/cordova-filechooser

2018-12-14 10:20 UTC, merged